Hw06 pipeline execution
zankrus/otus_homework pull request #8
Opened 2023-04-02 12:33 UTC by zankrus

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-04-02 19:49 UTC, itiulkanov commented on hw05_parallel_execution/run.go
Удалите, пожалуйста, файлы относящиеся к предыдущему ДЗ

2023-04-02 19:50 UTC, ityulkanov commented on hw05_parallel_execution/run.go
удалите, пожалуйста, файлы, относящиеся к предыдущему ДЗ

2023-04-02 19:55 UTC, ityulkanov commented on hw06_pipeline_execution/pipeline_test.go
> +		time.Sleep(time.Second)
```suggestion
		time.Sleep(time.Second)
```

2023-04-02 19:57 UTC, ityulkanov commented on hw06_pipeline_execution/pipeline.go
> +				log.Println(i)
Отладочные логи в PR лучше удалять

2023-04-02 20:50 UTC, itiulkanov commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Мы же вроде бы как должны вернуть однонаправленный канал, а использовать бидирекшнал только как промежуточный при работе с результатами этапов?

2023-04-02 20:51 UTC, itiulkanov commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Вижу, что это ломает дальнейшую логику, но рекомендую попробовать всё же не отходить от заданной изначально структуры

2023-04-02 20:52 UTC, ityulkanov commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Мы же вроде бы как должны вернуть однонаправленный канал, а использовать бидирекшнал только как промежуточный при работе с результатами этапов?

2023-04-02 20:59 UTC, ityulkanov commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Немного подскажу, при ренже по этапам, мы можем записывать в двунаправленный канал полученные из In и дальше забирать из него внутри ренжа, и использовать в этапах, а уже финальный результат возвращать однонаправленным каналом, как и задано

2023-04-02 21:01 UTC, ityulkanov requested changes
Роберт, вижу что сейчас решение работает, и тесты проходят, но предлагаю сделать следующим образом, я оставил комментарии, попробуйте реализовать решение используя их, если не получится, пишите, аппрувну вашу версию.

2023-04-09 09:15 UTC, zankrus commented on hw05_parallel_execution/run.go
Я ребейзнулся, должны пропасть

2023-04-09 09:22 UTC, zankrus commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Я честно вообще не понимаю, почему для компилятора норм:
Он ожидает, что я верну  объект типа OUT, но я возвращаю Bi и ему норм. Это кстати в тестах такая логика тоже
hw06_pipeline_execution/pipeline_test.go:20

2023-04-09 09:22 UTC, zankrus commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Иначе я не понимаю, как я могу записать данные в канал , с которого только читать можно

2023-04-09 09:29 UTC, zankrus commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Bi)
Вообщем все задания с каналами я вообще не понял, без тестов нифига не понятно. И зачем такое ограниение нужнно я тоже не понимаю ( про канал только чтения ). Можно же сделать,  двунаправленные каналы, просто не читать из них

2023-04-30 09:38 UTC, merged